---
# This playbook initializes X-Road automation environment


- hosts: lxd-servers
  roles:
    - role: init-lxd

- hosts: ss-servers, cs-servers, ca-servers
  become: yes
  become_user: root
  gather_facts: no
  pre_tasks:
    - name: 'Install python2'
      raw: apt-get -y install python
    
- hosts: cs-servers
  become: yes
  become_user: root
  roles:
    - xroad-cs

- hosts: ss-servers, cs-servers, ca-servers
  become: yes
  become_user: root
  gather_facts: no
  pre_tasks:
    - raw: apt-get -y install python

- hosts: ss-servers
  become: yes
  become_user: root
  roles:
    - xroad-ss
    
- hosts: ca-servers
  become: yes
  become_user: root
  pre_tasks:
    - raw: apt install openssl
  roles:
    - role: xroad-ca
      tags: [ 'ca' ]
