---
# This playbook initializes X-Road environment


- hosts: lxd-servers
  roles:
    - role: init-lxd
  tags:
    - init
    
- hosts: ss-servers, cs-servers, cp-servers, ca-servers
  become: yes
  become_user: root
  gather_facts: no
  pre_tasks:
    - name: 'Install python2'
      raw: apt-get -y install python
  tags:
    - init
    
- hosts: cs-servers
  become: yes
  become_user: root
  roles:
    - xroad-cs
  tags:
    cs

- hosts: cp-servers
  become: yes
  become_user: root
  roles:
    - xroad-cp
  tags:
    - cp

- hosts: ss-servers, cs-servers, cp-servers, ca-servers
  become: yes
  become_user: root
  gather_facts: no
  pre_tasks:
    - raw: apt-get -y install python

- hosts: ss-servers
  become: yes
  become_user: root
  roles:
    - xroad-ss
  tags:
    - ss
    
- hosts: ca-servers
  become: yes
  become_user: root
  pre_tasks:
    - raw: apt install openssl
  roles:
    - role: xroad-ca
      tags: [ 'ca' ]
