---
- name: Update all packages to the latest version
  apt:
    force: yes
    upgrade: dist

- name: "update apt cache"
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: "install configuration proxy"
  apt:
    name: "{{ item }}"
    state: present
    force: yes
  when: ansible_os_family == "Debian"
  with_items:
    - xroad-confproxy

