---
- name: install epel repo
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"

- name: xroad repo
  template:
    src: "palveluvayla.repo.j2"
    dest: "/etc/yum.repos.d/palveluvayla.repo"
    owner: root
    group: root
    mode: 0644
